name: CI do Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes e coletar cobertura
        run: npm run test:cov

      - name: Enviar relatório de cobertura para o Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true