name: Backend CI & Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Garantir permissão de execução para o Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Rebuild sqlite3 for CI environment
      run: npm rebuild sqlite3 --update-binary

    - name: Run tests and generate coverage report
      run: npm test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}